import Navbar from "@/components/Navbar";
import "../styles/main.scss";
import Footer from "@/components/Footer";
import Banner from "@/components/Banner";

export const metadata = {
  title: "Zilla Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Banner />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
